export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const UPDATE_ME_REQUEST = 'UPDATE_ME_REQUEST';
export const UPDATE_ME_SUCCESS = 'UPDATE_ME_SUCCESS';
export const UPDATE_ME_FAILURE = 'UPDATE_ME_FAILURE';

export const GET_MAIN_INFO_REQUEST = 'GET_MAIN_INFO_REQUEST';
export const GET_MAIN_INFO_SUCCESS = 'GET_MAIN_INFO_SUCCESS';
export const GET_MAIN_INFO_FAILURE = 'GET_MAIN_INFO_FAILURE';

export const UPDATE_PHONE_AND_NOTIFICATIONS_REQUEST = 'UPDATE_PHONE_AND_NOTIFICATIONS_REQUEST';
export const UPDATE_PHONE_AND_NOTIFICATIONS_SUCCESS = 'UPDATE_PHONE_AND_NOTIFICATIONS_SUCCESS';
export const UPDATE_PHONE_AND_NOTIFICATIONS_FAILURE = 'UPDATE_PHONE_AND_NOTIFICATIONS_FAILURE';

export const GET_ME_REQUEST = 'GET_ME_REQUEST';
export const GET_ME_SUCCESS = 'GET_ME_SUCCESS';
export const GET_ME_FAILURE = 'GET_ME_FAILURE';

export const GET_USER_EDIT_REQUEST = 'GET_USER_EDIT_REQUEST';
export const GET_USER_EDIT_SUCCESS = 'GET_USER_EDIT_SUCCESS';
export const GET_USER_EDIT_FAILURE = 'GET_USER_EDIT_FAILURE';

export const GET_USER_INFO_FOR_EDIT_REQUEST = 'GET_USER_INFO_FOR_EDIT_REQUEST';
export const GET_USER_INFO_FOR_EDIT_SUCCESS = 'GET_USER_INFO_FOR_EDIT_SUCCESS';
export const GET_USER_INFO_FOR_EDIT_FAILURE = 'GET_USER_INFO_FOR_EDIT_FAILURE';