export const UPDATE_PAYMENT_FORM_CARD_NUMBER = 'UPDATE_PAYMENT_FORM_CARD_NUMBER';
export const UPDATE_PAYMENT_FORM_EXPIRATION = 'UPDATE_PAYMENT_FORM_EXPIRATION';
export const UPDATE_PAYMENT_FORM_CVC = 'UPDATE_PAYMENT_FORM_CVC';