export const GET_FORMATIONS_REQUEST = 'GET_FORMATIONS_REQUEST';
export const GET_FORMATIONS_SUCCESS = 'GET_FORMATIONS_SUCCESS';
export const GET_FORMATIONS_FAILURE = 'GET_FORMATIONS_FAILURE';

export const GET_FORMATION_REQUEST = 'GET_FORMATION_REQUEST';
export const GET_FORMATION_SUCCESS = 'GET_FORMATION_SUCCESS';
export const GET_FORMATION_FAILURE = 'GET_FORMATION_FAILURE';

export const GET_MODULES_REQUEST = 'GET_MODULES_REQUEST';
export const GET_MODULES_SUCCESS = 'GET_MODULES_SUCCESS';
export const GET_MODULES_FAILURE = 'GET_MODULES_FAILURE';
