export const GET_ARTICLE_REQUEST = 'GET_ARTICLE_REQUEST';
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';
export const GET_ARTICLE_FAILURE = 'GET_ARTICLE_FAILURE';

export const GET_ARTICLES_REQUEST = 'GET_ARTICLES_REQUEST';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAILURE = 'GET_ARTICLES_FAILURE';

export const RESET_ARTICLES = 'RESET_ARTICLES';

export const LOAD_MORE_ARTICLES_REQUEST = 'LOAD_MORE_ARTICLES_REQUEST';
export const LOAD_MORE_ARTICLES_SUCCESS = 'LOAD_MORE_ARTICLES_SUCCESS';
export const LOAD_MORE_ARTICLES_FAILURE = 'LOAD_MORE_ARTICLES_FAILURE';

export const LOAD_MORE_RESOURCE_ARTICLES_REQUEST = 'LOAD_MORE_RESOURCE_ARTICLES_REQUEST';
export const LOAD_MORE_RESOURCE_ARTICLES_SUCCESS = 'LOAD_MORE_RESOURCE_ARTICLES_SUCCESS';
export const LOAD_MORE_RESOURCE_ARTICLES_FAILURE = 'LOAD_MORE_RESOURCE_ARTICLES_FAILURE';

export const GET_TOP_ARTICLE_REQUEST = 'GET_TOP_ARTICLE_REQUEST';
export const GET_TOP_ARTICLE_SUCCESS = 'GET_TOP_ARTICLE_SUCCESS';
export const GET_TOP_ARTICLE_FAILURE = 'GET_TOP_ARTICLE_FAILURE';

export const GET_HEAD_ARTICLES_REQUEST = 'GET_HEAD_ARTICLES_REQUEST';
export const GET_HEAD_ARTICLES_SUCCESS = 'GET_HEAD_ARTICLES_SUCCESS';
export const GET_HEAD_ARTICLES_FAILURE = 'GET_HEAD_ARTICLES_FAILURE';