export const GET_VIDEO_REQUEST = 'GET_VIDEO_REQUEST';
export const GET_VIDEO_SUCCESS = 'GET_VIDEO_SUCCESS';
export const GET_VIDEO_FAILURE = 'GET_VIDEO_FAILURE';

export const GET_VIDEOS_REQUEST = 'GET_VIDEOS_REQUEST';
export const GET_VIDEOS_SUCCESS = 'GET_VIDEOS_SUCCESS';
export const GET_VIDEOS_FAILURE = 'GET_VIDEOS_FAILURE';

export const RESET_VIDEOS = 'RESET_VIDEOS';

export const LOAD_MORE_VIDEOS_REQUEST = 'LOAD_MORE_VIDEOS_REQUEST';
export const LOAD_MORE_VIDEOS_SUCCESS = 'LOAD_MORE_VIDEOS_SUCCESS';
export const LOAD_MORE_VIDEOS_FAILURE = 'LOAD_MORE_VIDEOS_FAILURE';

export const LOAD_MORE_RESOURCE_VIDEOS_REQUEST = 'LOAD_MORE_RESOURCE_VIDEOS_REQUEST';
export const LOAD_MORE_RESOURCE_VIDEOS_SUCCESS = 'LOAD_MORE_RESOURCE_VIDEOS_SUCCESS';
export const LOAD_MORE_RESOURCE_VIDEOS_FAILURE = 'LOAD_MORE_RESOURCE_VIDEOS_FAILURE';

export const GET_TOP_VIDEO_REQUEST = 'GET_TOP_VIDEO_REQUEST';
export const GET_TOP_VIDEO_SUCCESS = 'GET_TOP_VIDEO_SUCCESS';
export const GET_TOP_VIDEO_FAILURE = 'GET_TOP_VIDEO_FAILURE';