export const CREATE_SUBSCRIPTION_REQUEST = 'CREATE_SUBSCRIPTION_REQUEST';
export const CREATE_SUBSCRIPTION_SUCCESS = 'CREATE_SUBSCRIPTION_SUCCESS';
export const CREATE_SUBSCRIPTION_FAILURE = 'CREATE_SUBSCRIPTION_FAILURE';

export const GET_CURRENT_SUBSCRIPTION_REQUEST = 'GET_CURRENT_SUBSCRIPTION_REQUEST';
export const GET_CURRENT_SUBSCRIPTION_SUCCESS = 'GET_CURRENT_SUBSCRIPTION_SUCCESS';
export const GET_CURRENT_SUBSCRIPTION_FAILURE = 'GET_CURRENT_SUBSCRIPTION_FAILURE';

export const CALCULATE_PRORATION_REQUEST = 'CALCULATE_PRORATION_REQUEST';
export const CALCULATE_PRORATION_SUCCESS = 'CALCULATE_PRORATION_SUCCESS';
export const CALCULATE_PRORATION_FAILURE = 'CALCULATE_PRORATION_FAILURE';

export const SWITCH_SUBSCRIPTION_REQUEST = 'SWITCH_SUBSCRIPTION_REQUEST';
export const SWITCH_SUBSCRIPTION_SUCCESS = 'SWITCH_SUBSCRIPTION_SUCCESS';
export const SWITCH_SUBSCRIPTION_FAILURE = 'SWITCH_SUBSCRIPTION_FAILURE';

export const GET_INVOICES_REQUEST = 'GET_INVOICES_REQUEST';
export const GET_INVOICES_SUCCESS = 'GET_INVOICES_SUCCESS';
export const GET_INVOICES_FAILURE = 'GET_INVOICES_FAILURE';

export const CANCEL_SUBSCRIPTION_REQUEST = 'CANCEL_SUBSCRIPTION_REQUEST';
export const CANCEL_SUBSCRIPTION_SUCCESS = 'CANCEL_SUBSCRIPTION_SUCCESS';
export const CANCEL_SUBSCRIPTION_FAILURE = 'CANCEL_SUBSCRIPTION_FAILURE';