export const SET_RESPONSE_HEADERS = 'SET_RESPONSE_HEADERS';

export const SET_INTERCEPTOR_UPLOAD_PROGRESS = 'SET_INTERCEPTOR_UPLOAD_PROGRESS';
export const SET_INTERCEPTOR_DOWNLOAD_PROGRESS = 'SET_INTERCEPTOR_DOWNLOAD_PROGRESS';