development:
  forest_env_secret: 4fbcd88f418eac37416e2a0d4a61f8be763529b3c51dd721218a6bb83fd5f1e0
  forest_auth_secret: XxVIV-O8LRCzPi173N7nbA
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
